name: React CI/CD with Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configura o Node.js para instalar dependências
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Instala as dependências do React
      - name: Install dependencies
        run: npm install

      # Roda os testes, se houver
      - name: Run tests
        run: npm test --if-present

      # Faz o build da aplicação React
      - name: Build React app
        run: npm run build

      # Faz o build da imagem Docker
      - name: Build Docker image
        run: docker build -t my-react-app .

      # (Opcional) Testa a imagem criada
      - name: Run Docker container for testing
        run: docker run --rm -d -p 3000:3000 my-react-app

      # (Opcional) Push da imagem para DockerHub ou outro registry
      # Descomente abaixo se quiser publicar a imagem
      # - name: Login to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Push Docker image
      #   run: docker push my-react-app

